server:
  port: ${PORT:8761}

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:eurekaserver-production-adff.up.railway.app}
  server:
    renewal-percent-threshold: 0.90